[package]
name = "tapyrus-spv"
version = "0.1.0"
authors = ["Kohei Taniguchi <kohei@chaintope.com>"]
edition = "2018"

[dependencies]
bitcoin = "0.18.0"
log="0.4"
simple_logger="1.3"
tokio = "0.1.22"
rand = "0.7.0"
futures-preview = { version = "0.3.0-alpha.17", features = ["io-compat"] }
bytes = "0.4.12"